name: SKY UX CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    tags:
      - '*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && 'npm' || '' }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - uses: blackbaud/skyux-sdk-actions@9b008f6a754faf49332de790d3e4cdc85918efdd # v1.1.1
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          project: 'addin-client'
          code-coverage-browser-set: speedy
